const ZHAD = [
  {
    KEY: "01",
    ID: "NUMBERCAMERA",
    POSITION: "1",
    LABEL: "NUMBERCAMERA",
    NAME: "NUMBERCAMERA",
    TYPE: "number",
    MAX_LENGTH: 18,
    LOW_LENGTH: 0,
    MANDATORY: false,
    VISIBLE: false,
    DISABLED: true,
    VALUE: "",
    FOCUS: false,
    FOREING_DAO: {},
  },
  {
    KEY: "11",
    ID: "ID",
    POSITION: "1",
    LABEL: "ID",
    NAME: "ID",
    TYPE: "hidden",
    MAX_LENGTH: 18,
    LOW_LENGTH: 0,
    MANDATORY: true,
    VISIBLE: false,
    DISABLED: true,
    VALUE: "",
    FOCUS: false,
    FOREING_DAO: {},
  },
  {
    KEY: "21",
    ID: "OWNER",
    POSITION: "2",
    LABEL: "Propietario",
    NAME: "OWNER",
    TYPE: "foreign",
    MAX_LENGTH: 18,
    LOW_LENGTH: 0,
    MANDATORY: true,
    VISIBLE: true,
    DISABLED: false,
    VALUE: "",
    FOCUS: false,
    FOREING_DAO: { 1: "Celsia" } /* {
			dataElements: { 1: 'Celsia' },
			MODULENAME: 'generic',
			DAONAME: '483',
			SHOWCOLUMNNAME: 'name',
			TITTLE: 'Propietario',
		} */,
  },
  {
    KEY: "31",
    ID: "OPERATORCABLE",
    POSITION: "2",
    LABEL: "OPERATORCABLE",
    NAME: "OPERATORCABLE",
    TYPE: "text",
    MAX_LENGTH: 30,
    LOW_LENGTH: 0,
    MANDATORY: false,
    VISIBLE: false,
    DISABLED: true,
    VALUE: "",
    FOCUS: false,
    FOREING_DAO: {},
  },
  {
    KEY: "41",
    ID: "PHOTOGRAPHICRECORD",
    POSITION: "3",
    LABEL: "Registro fotográfico",
    NAME: "PHOTOGRAPHICRECORD",
    TYPE: "text",
    MAX_LENGTH: 30,
    LOW_LENGTH: 0,
    MANDATORY: false,
    VISIBLE: false,
    DISABLED: true,
    VALUE: "",
    FOCUS: false,
    FOREING_DAO: {},
  },
  {
    KEY: "51",
    ID: "LOCATION",
    POSITION: "4",
    LABEL: "Ubicación",
    NAME: "LOCATION",
    TYPE: "location",
    MAX_LENGTH: 300,
    LOW_LENGTH: 0,
    MANDATORY: true,
    VISIBLE: true,
    DISABLED: false,
    VALUE: "",
    FOCUS: false,
    FOREING_DAO: {},
  },
  {
    KEY: "61",
    ID: "TYPE",
    POSITION: "5",
    LABEL: "Tipo",
    NAME: "TYPE",
    TYPE: "foreign",
    MAX_LENGTH: 18,
    LOW_LENGTH: 0,
    MANDATORY: true,
    VISIBLE: true,
    DISABLED: false,
    VALUE: "",
    FOCUS: false,
    FOREING_DAO: { 1: "F1", 2: "2F1", 3: "F2" } /* {
			dataElements: { 1: 'F1', 2: '2F1', 3: 'F2' },
			MODULENAME: 'generic',
			DAONAME: '482',
			SHOWCOLUMNNAME: 'name',
			TITTLE: 'Tipo',
		} */,
  },
  {
    KEY: "71",
    ID: "DATECREATE",
    POSITION: "6",
    LABEL: "DATECREATE",
    NAME: "DATECREATE",
    TYPE: "date",
    LOW_LENGTH: 0,
    MANDATORY: false,
    VISIBLE: false,
    DISABLED: false,
    VALUE: "",
    FOCUS: false,
    FOREING_DAO: {},
  },
  {
    KEY: "81",
    ID: "IDPROJECT",
    POSITION: "7",
    LABEL: "Identificador del proyecto",
    NAME: "IDPROJECT",
    TYPE: "number",
    MAX_LENGTH: 18,
    LOW_LENGTH: 0,
    MANDATORY: false,
    VISIBLE: false,
    DISABLED: true,
    VALUE: "",
    FOCUS: false,
    FOREING_DAO: {},
  },
  {
    KEY: "91",
    ID: "IDPROJECTROUTE",
    POSITION: "8",
    LABEL: "IDPROJECTROUTE",
    NAME: "IDPROJECTROUTE",
    TYPE: "number",
    MAX_LENGTH: 5,
    LOW_LENGTH: 0,
    MANDATORY: false,
    VISIBLE: true,
    DISABLED: false,
    VALUE: "",
    FOCUS: false,
    FOREING_DAO: {},
  },
  {
    KEY: "101",
    ID: "NAME",
    POSITION: "9",
    LABEL: "Nombre",
    NAME: "NAME",
    TYPE: "text",
    MAX_LENGTH: 60,
    LOW_LENGTH: 0,
    MANDATORY: true,
    VISIBLE: true,
    DISABLED: false,
    VALUE: "",
    FOCUS: false,
    FOREING_DAO: {},
  },
  {
    KEY: "111",
    ID: "ICON",
    POSITION: "10",
    LABEL: "ICON",
    NAME: "ICON",
    TYPE: "ICONO",
    MAX_LENGTH: 120,
    LOW_LENGTH: 0,
    MANDATORY: false,
    VISIBLE: false,
    DISABLED: true,
    VALUE: "",
    FOCUS: false,
    FOREING_DAO: {},
  },
  {
    KEY: "121",
    ID: "DESCRIPTION",
    POSITION: "11",
    LABEL: "Descripción",
    NAME: "DESCRIPTION",
    TYPE: "text",
    MAX_LENGTH: 120,
    LOW_LENGTH: 0,
    MANDATORY: true,
    VISIBLE: true,
    DISABLED: false,
    VALUE: "",
    FOCUS: false,
    FOREING_DAO: {},
  },
];

const FORM_WIZARD_1 = [
  {
    KEY: "51",
    ID: "LOCATION",
    POSITION: "4",
    LABEL: "Ubicación",
    NAME: "LOCATION",
    TYPE: "location",
    MAX_LENGTH: 300,
    LOW_LENGTH: 0,
    MANDATORY: true,
    VISIBLE: true,
    DISABLED: false,
    VALUE: "",
    FOCUS: false,
    FOREING_DAO: {},
  },
  {
    KEY: "1",
    ID: "Barrio",
    POSITION: "5",
    LABEL: "Barrio",
    NAME: "Barrio",
    TYPE: "foreign",
    MANDATORY: true,
    VISIBLE: true,
    VALUE: "",
    FOCUS: false,
    FOREING_DAO: { 1: "Cali", 2: "Palmira", 3: "Jamundi" },
  },
  {
    KEY: "2",
    ID: "Vprincipal",
    POSITION: "5",
    LABEL: "Via principal",
    NAME: "Vprincipal",
    TYPE: "foreign",
    MAX_LENGTH: 18,
    LOW_LENGTH: 0,
    MANDATORY: true,
    VISIBLE: true,
    DISABLED: false,
    VALUE: "",
    FOCUS: false,
    FOREING_DAO: { 1: "Calle", 2: "Carrera", 3: "Avenida" },
  },
  {
    KEY: "3",
    ID: "Cprincipal",
    POSITION: "9",
    LABEL: "Complemento principal",
    NAME: "Cprincipal",
    TYPE: "text",
    MAX_LENGTH: 30,
    LOW_LENGTH: 0,
    MANDATORY: true,
    VISIBLE: true,
    DISABLED: false,
    VALUE: "",
    FOCUS: false,
    FOREING_DAO: {},
  },
  {
    KEY: "4",
    ID: "CrdPrincipal",
    POSITION: "5",
    LABEL: "Cardinalidad",
    NAME: "Cardinalidad",
    TYPE: "select",
    MAX_LENGTH: 18,
    LOW_LENGTH: 0,
    MANDATORY: false,
    VISIBLE: true,
    DISABLED: false,
    VALUE: [1, 9],
    FOCUS: false,
    FOREING_DAO: { 1: "Norte", 5: "Sur", 3: "Oeste", 9: "Este" },
  },
  {
    KEY: "5",
    ID: "BPrincipal",
    POSITION: "9",
    LABEL: "BIS",
    NAME: "BPrincipal",
    TYPE: "boolean",
    MAX_LENGTH: 30,
    LOW_LENGTH: 0,
    MANDATORY: false,
    VISIBLE: true,
    DISABLED: false,
    VALUE: false,
    FOCUS: false,
    FOREING_DAO: {},
  },
];

const FORM_WIZARD_2 = [
  {
    KEY: "6",
    ID: "Vgeneradora",
    POSITION: "5",
    LABEL: "Via generadora",
    NAME: "Vgeneradora",
    TYPE: "foreign",
    MAX_LENGTH: 18,
    LOW_LENGTH: 0,
    MANDATORY: false,
    VISIBLE: true,
    DISABLED: false,
    VALUE: "",
    FOCUS: false,
    FOREING_DAO: { 1: "Calle", 2: "Carrera", 3: "Avenida" },
  },
  {
    KEY: "7",
    ID: "Cgenerador",
    POSITION: "9",
    LABEL: "Complemento generador",
    NAME: "Cgenerador",
    TYPE: "text",
    MAX_LENGTH: 30,
    LOW_LENGTH: 0,
    MANDATORY: false,
    VISIBLE: true,
    DISABLED: false,
    VALUE: "",
    FOCUS: false,
    FOREING_DAO: {},
  },
  {
    KEY: "8",
    ID: "CrdGeneradora",
    POSITION: "5",
    LABEL: "Cardinalidad",
    NAME: "Cardinalidad",
    TYPE: "foreign",
    MAX_LENGTH: 18,
    LOW_LENGTH: 0,
    MANDATORY: false,
    VISIBLE: true,
    DISABLED: false,
    VALUE: "",
    FOCUS: false,
    FOREING_DAO: { 1: "Norte", 2: "Sur", 3: "Oeste", 4: "Este" },
  },
  {
    KEY: "9",
    ID: "Bgenerador",
    POSITION: "9",
    LABEL: "BIS",
    NAME: "Bgenerador",
    TYPE: "boolean",
    MAX_LENGTH: 30,
    LOW_LENGTH: 0,
    MANDATORY: false,
    VISIBLE: true,
    DISABLED: false,
    VALUE: true,
    FOCUS: false,
    FOREING_DAO: {},
  },
];

const FORM_WIZARD = [...FORM_WIZARD_1, ...FORM_WIZARD_2];

export { ZHAD, FORM_WIZARD_1, FORM_WIZARD_2, FORM_WIZARD };
